# Generated by Django 5.2.17 on 2026-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DELUXE', 'Deluxe')], default='NORMAL', max_length=20),
        ),
    ]
